### ISSUE TITLE
TOTP configuration 

### ISSUE THREAD

**Issue by Prajithp** [osstech-jp/openldap#2]
Hi,

 Could you please add more info about the TOTP modules? I could not find any single article about this.

**Comment by hamano** [comment]
Here is working space for back-wt.
You should ask the question to OpenLDAP Technical ML.
Thank you.

**Comment by erthink** [comment]
@Prajithp, take look to https://github.com/leo-yuriev/ReOpenLDAP.

There building and installing of all contrib-modules are integrated.
For instance the `totp` is also available with a man-page.

You just needs to run `./confgure  --enable-modules --enable-contrib ...`

**Comment by Prajithp** [comment]
@leo-yuriev Thank you so much. Will look into it when I get time and update you
